### ISSUE TITLE
注解的使用方式可以说明下吗?

### ISSUE THREAD

**Issue by wenber-yu** [friendsofhyperf/lock#2]
使用注解的话, 会自动释放锁吗?

**Comment by huangdijia** [comment]
注解跟#[Inject]功能差不多，只是将属性绑定一个lock对象。

**Comment by wenber-yu** [comment]
哦哦好的, 我以为是方法级的.

**Comment by huangdijia** [comment]
方法级的应用场景是什么样的？可以说说，我看看能不能实现

**Comment by wenber-yu** [comment]
例如下单场景, 在下单方法`create`中, 需要加锁, 然后运行一个事务, 由try/catch包括, 无论事务执行成功与否, 在finally中都会将锁释放.
如果使用注解, 则在`create`方法上启用加锁注解, 设置好锁名称, 等待时间, 不需要再在`create`方法内部再显示的声明加锁步骤.

可以将try/catch/finally移动到加锁注解切面类中进行统一加锁与释放.

**Comment by huangdijia** [comment]
> 例如下单场景, 在下单方法`create`中, 需要加锁, 然后运行一个事务, 由try/catch包括, 无论事务执行成功与否, 在finally中都会将锁释放.
> 
> 如果使用注解, 则在`create`方法上启用加锁注解, 设置好锁名称, 等待时间, 不需要再在`create`方法内部再显示的声明加锁步骤.
> 
> 
> 
> 可以将try/catch/finally移动到加锁注解切面类中进行统一加锁与释放.

这个应该用AOP就能解决，不过直接抛异常好像不太好

**Comment by wenber-yu** [comment]
aop中的抛异常应该是将使用注解的方法中的异常原样抛出, 这样不会影响业务中的逻辑. 在aop中增加try/catch/finally
只是为了能正常把锁释放掉, 而不用去关注具体业务逻辑. 
如这个自定义的事务注解:
```php
#[Aspect]
class TransactionAspect extends AbstractAspect
{
    public $annotations = [
        Transaction::class,
    ];

    /**
     * @param  ProceedingJoinPoint  $proceedingJoinPoint
     *
     * @return mixed
     */
    public function process(ProceedingJoinPoint $proceedingJoinPoint): mixed
    {
        /** @var Transaction $transaction */
        if (isset($proceedingJoinPoint->getAnnotationMetadata()->method[Transaction::class])) {
            $transaction = $proceedingJoinPoint->getAnnotationMetadata()->method[Transaction::class];
        }
        try {
            Db::beginTransaction();
            $number = 0;
            $retry = (int)$transaction->retry;
            do {
                $result = $proceedingJoinPoint->process();
                if (!is_null($result)) {
                    break;
                }
                ++$number;
            } while ($number < $retry);
            Db::commit();
        } catch (Throwable $e) {
            Db::rollBack();
            throw $e;
        }

        return $result;
    }
}
```

**Comment by huangdijia** [comment]
看起来像是把lock::get()通过注解把请求的方法包起来差不多，但是这会影响到返回值吧，如果获取锁失败，要怎么处理？

**Comment by wenber-yu** [comment]
这个我认为就是使用者自己的取舍了, 反正获取锁失败或者获取锁等待超时,都会有异常抛出. 
如果使用锁注解, 在关于锁的异常时,直接抛出就可以了. 不影响其他地方.
如果是在方法内部使用锁相关方法, 锁异常也是需要另外捕获来做处理的. 这个我倒觉得无所谓了.

**Comment by huangdijia** [comment]
伪代码：

```php
#[Aspect]
class TransactionAspect extends AbstractAspect
{
    public $annotations = [
        Lock::class,
    ];

    /**
     * @param  ProceedingJoinPoint  $proceedingJoinPoint
     *
     * @return mixed
     */
    public function process(ProceedingJoinPoint $proceedingJoinPoint): mixed
    {
        $lock = lock('xxxx', 10); // 从注解获取 name 和 seconds

        try {
            if (!$lock->get()) throw \Exception('Get lock fails');

            return $proceedingJoinPoint->process();
        } finally {
            $lock->release();
        }
    }
}
```

类似这样？

**Comment by wenber-yu** [comment]
嗯, 差不多这个意思, 
如果注解参数中有获取等待的话, 就使用block
$proceedingJoinPoint->process();这个我觉得怎么也得trycatch捕获下, 如果业务方法抛出异常, 会导致无法释放锁.

**Comment by huangdijia** [comment]
> 嗯, 差不多这个意思, 如果注解参数中有获取等待的话, 就使用block $proceedingJoinPoint->process();这个我觉得怎么也得trycatch捕获下, 如果业务方法抛出异常, 会导致无法释放锁.

我上面改了一下

**Comment by huangdijia** [comment]
https://github.com/friendsofhyperf/components/pull/44/files

@wilbur-yu 你看看是不是这样样子

**Comment by wenber-yu** [comment]
NB, 就是这么个意思

**Comment by Chance-fyi** [comment]
> https://github.com/friendsofhyperf/components/pull/44/files
> 
> @wilbur-yu 你看看是不是这样样子

为什么最后没有合并

**Comment by huangdijia** [comment]
> 为什么最后没有合并

这用法有歧义，不是很推荐。
