### ISSUE TITLE
锁前缀没有共用cache中配置的prefix吗?

### ISSUE THREAD

**Issue by wenber-yu** [friendsofhyperf/lock#3]
我在cache中配置了prefix, 没有生效, 在redis中配置了prefix也没有生效.
Laravel中lock是共用cache的配置的.
我现在是现想统一一下多框架共用一个缓存前缀,

**Comment by huangdijia** [comment]
hyperf 的 redis 本来也没有 prefix 吧？

**Comment by wenber-yu** [comment]
嗯, redis.没有, 但是cache有的. 
我以为是像laravel那样, 也是归类在了cache中.

**Comment by huangdijia** [comment]
你是怎么用的？

**Comment by wenber-yu** [comment]
使用是按文档中的, 
只是我现在有两个项目, 一个laravel, 一个hyperf, 想把缓存统一下, 所以就有了这个问题, 
现在我是在hyperf中加锁的时候, 锁名称前边我加了固定的前缀就可以了.
