### ISSUE TITLE
Coroutine/cache lock

### ISSUE THREAD

**Issue by n-hor** [friendsofhyperf/lock#5]
Is it safe to use coroutine/cache locking if there is more than one worker running? I want to block access to a swoole table for all workers if one of them updates it.

**Comment by huangdijia** [comment]
Yes, the coroutine is safe.

**Comment by n-hor** [comment]
if i use 'co' as driver, i got this error

`Entry "FriendsOfHyperf\Lock\Driver\CoroutineLock" cannot be resolved: Entry "Hyperf\Cache\Driver\CoroutineMemoryDriver" cannot be resolved: Parameter $config of __construct() has no value defined or guessable`

Code:

```
 $lock = lock('foo', 10, driver: 'co');
```

lock config:

```
  'co' => [
        'driver' => FriendsOfHyperf\Lock\Driver\CoroutineLock::class,
        'constructor' => [
            'prefix' => 'lock:',
            'sleepMilliseconds' => 25,
        ],
    ],
```

**Comment by huangdijia** [comment]
I just fixed this problem, please update to the latest version and try again

**Comment by n-hor** [comment]
Does coroutine locking driver only work if the server is running in coroutine mode? For the swole process mode, no blocking occurs

**Comment by huangdijia** [comment]
This driver is only applicable within the coroutine life cycle
